import { spinDrills } from './spin-scenes';

export class SpinDrillsPage {
  constructor(start:(ids:string[],rounds:number)=>void) {
    const section=document.createElement('section');section.id='spin-drills-page';section.className='page';section.hidden=true;
    const groups=[...new Set(spinDrills.map(drill=>drill.group??'Reference examples'))];
    const columns=['i','j','l','s','t','z'].map(piece=>`<fieldset class="spin-piece-column" data-piece="${piece}"><legend><span>${piece.toUpperCase()}</span><input class="spin-select-piece" type="checkbox" aria-label="Select all ${piece.toUpperCase()} drills" title="Select all ${piece.toUpperCase()} drills"></legend>${groups.map(group=>{const drills=spinDrills.filter(drill=>drill.piece===piece&&(drill.group??'Reference examples')===group);return drills.length?`<div class="spin-drill-group"><div class="spin-drill-heading"><h3>${group}</h3><input class="spin-select-group" type="checkbox" aria-label="Select all ${piece.toUpperCase()} ${group}" title="Select all ${group}"></div><div class="chip-options">${drills.map(drill=>`<label><input type="checkbox" name="spin-drill-type" value="${drill.id}" ${['tsd','mini'].includes(drill.id)?'checked':''}><span>${drill.name}${drill.source?` <small>TTT ${drill.source.split('lesson ')[1]}</small>`:''}</span></label>`).join('')}</div></div>`:'';}).join('')}</fieldset>`).join('');
    section.innerHTML=`<h2>Spin drills</h2><p class="muted">Choose several spins or rotation techniques. Each round randomizes the slot and surrounding supported terrain, then checks the solution with the active mode's rules.</p><p class="muted">The <a href="https://teatube.cn/ttt/" target="_blank" rel="noopener">TTT rotation course</a> includes slide-ins, reverse entries, overhangs, S/Z tucks, I kicks, NEO, FIN, ISO and repeated descent turns. Course numbers identify the related lesson.</p><form id="spin-drill-form"><label>Find a drill<input id="spin-drill-filter" type="search" placeholder="Piece, technique or lesson number"></label><div class="spin-piece-columns">${columns}</div><div class="page-toolbar"><button id="spin-drill-all" type="button" class="secondary small">Select visible</button><button id="spin-drill-none" type="button" class="secondary small">Clear selection</button></div><label class="select-row">Session length<select id="spin-drill-rounds"><option value="0">Endless</option><option value="10">10 boards</option><option value="20">20 boards</option><option value="50">50 boards</option></select></label><p class="muted">Each selected type appears before the shuffled set repeats. Solve the round's spin goal to advance. Perfect finesse retries extra inputs when enabled. Each board is analyzed once; movement and retries reuse the results. Hints count movement and rotation inputs, excluding soft drop and hard drop.</p><p class="muted">All-Mini+ scores non-T spins as Mini. Other modes can score them differently. TTT rotation lessons require the designated slot and a valid entry. Ordinary drops and free-air rotations do not complete them.</p><button type="submit">Start Spin drills</button><a class="secondary" href="#spin">Back to Spin</a><p id="spin-drill-form-status" role="status"></p></form>`;
    document.getElementById('play-page')!.after(section);
    const inputs=()=>Array.from(section.querySelectorAll<HTMLInputElement>('input[name="spin-drill-type"]')),rounds=section.querySelector<HTMLSelectElement>('#spin-drill-rounds')!;
    try{const saved=JSON.parse(localStorage.getItem('tetrio-trainer-spin-drills-v1')??'null');if(saved&&Array.isArray(saved.ids)){const ids=saved.ids.filter((id:unknown)=>spinDrills.some(drill=>drill.id===id));inputs().forEach(input=>{input.checked=ids.includes(input.value);});if(ids.length!==saved.ids.length)localStorage.setItem('tetrio-trainer-spin-drills-v1',JSON.stringify({...saved,ids}));if([0,10,20,50].includes(saved.rounds))rounds.value=String(saved.rounds);}}catch{}
    section.querySelector<HTMLInputElement>('#spin-drill-filter')!.addEventListener('input',event=>{const query=(event.target as HTMLInputElement).value.toLowerCase();inputs().forEach(input=>{input.closest('label')!.hidden=!`${input.value} ${input.closest('label')!.textContent}`.toLowerCase().includes(query);});});
    const syncSelection=()=>{section.querySelectorAll<HTMLInputElement>('.spin-select-piece,.spin-select-group').forEach(toggle=>{const scope=toggle.closest(toggle.classList.contains('spin-select-piece')?'.spin-piece-column':'.spin-drill-group')!,items=Array.from(scope.querySelectorAll<HTMLInputElement>('input[name="spin-drill-type"]')),count=items.filter(input=>input.checked).length;toggle.checked=count===items.length;toggle.indeterminate=count>0&&count<items.length;});};
    section.addEventListener('change',event=>{const toggle=event.target as HTMLInputElement;if(toggle.matches('.spin-select-piece,.spin-select-group')){const scope=toggle.closest(toggle.classList.contains('spin-select-piece')?'.spin-piece-column':'.spin-drill-group')!;scope.querySelectorAll<HTMLInputElement>('input[name="spin-drill-type"]').forEach(input=>{input.checked=toggle.checked;});}syncSelection();});
    syncSelection();
    for(const [id,checked] of [['all',true],['none',false]] as const)section.querySelector(`#spin-drill-${id}`)!.addEventListener('click',()=>{inputs().forEach(input=>{if(!checked||!input.closest('label')!.hidden)input.checked=checked;});syncSelection();});
    section.querySelector('form')!.addEventListener('submit',event=>{
      event.preventDefault();const ids=inputs().filter(input=>input.checked).map(input=>input.value);
      try{if(!ids.length)throw new Error('Select at least one spin or kick.');start(ids,Number(rounds.value));localStorage.setItem('tetrio-trainer-spin-drills-v1',JSON.stringify({ids,rounds:Number(rounds.value)}));location.hash='spin';}catch(error){section.querySelector('#spin-drill-form-status')!.textContent=(error as Error).message;}
    });
  }
}
